version: '2'
services:
  elasticsearch:
    image: 'elasticsearch:5.1-alpine'
  datasets:
    image: 'circleci/postgres:9.6-alpine'
    command: ls -la /amir
    volumes:
      - '/var/lib/docker/volumes/${{CF_VOLUME}}/_data/demochat/extras/emotes/:/amir'
